[package]
name = "torch_test"
version = "0.1.0"
authors = ["Kahlil Abreu <kahlil.abreu@holmusk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.1.3"
failure = "0.1.6"
